apps/products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.products, name="products"),
    url(r'^new$', views.new_product, name="new_product"),
    url(r'^create$', views.create_new_product, name="create_new_product"),
    url(r'^destroy/(?P<id>\d+)$', views.destroy, name="destroy"),
    url(r'^show/(?P<id>\d+)$', views.show, name="show"),
    url(r'^update/(?P<id>\d+)$', views.update, name="update"),
    url(r'^edit/(?P<id>\d+)$', views.edit, name="edit")
]

restful_routes/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.products.urls', namespace = 'products')),
    url(r'^products/', include('apps.products.urls', namespace='products'))
]

apps/products/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.


class ProductManager(models.Manager):
    def create_new_product(self, product_data):
        errors = []

        if not product_data['name']:
            errors.append("Name can not be blank.")
        if not product_data['description']:
            errors.append("Description can not be blank")
        if not product_data['price']:
            errors.append("Price can not be blank.")

        response = {}

        if errors:
            response['errors'] = errors
            response['created'] = False
        else:
            new_product = self.create(name=product_data['name'], description=product_data['description'], price=product_data['price'])
            response['created'] = True
            response['new_product'] = new_product
        return response

    def update_product(self, id, product_data):
        errors = []

        if not product_data['name']:
            errors.append("Name can not be blank.")
        if not product_data['description']:
            errors.append("Description can not be blank")
        if not product_data['price']:
            errors.append("Price can not be blank.")

        response = {}
        if errors:
            response['errors'] = errors
            response['updated'] = False
        else:
            product = self.get(id=id)
            product.name = product_data['name']
            product.description = product_data['description']
            product.price = product_data['price']
            product.save()
            response['updated'] = True
            response['updated_product'] = product
        return response


class Product(models.Model):
    name = models.CharField(max_length=45)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ProductManager()

apps/products/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import Product
#from django.core.urlresolvers import reverse
# Create your views here.


def products(request):
    context = {"products": Product.objects.all()}
    return render(request, 'products/products.html', context)


def new_product(request):
    return render(request, 'products/new_product.html')


def create_new_product(request):
    if request.method == "POST":
        product_data = Product.objects.create_new_product(request.POST)
        if product_data['created']:
            messages.success(request, "Successfully added {}.".format(product_data['new_product'].name))
        else:
            for error in product_data['errors']:
                messages.error(request, error)
        return redirect(reverse('products:new_product'))


def show(request, id):
    context = {"product": Product.objects.get(id=id)}
    return render(request, 'products/show_product.html', context)


def update(request, id):
    if request.method == "POST":
        product_data = Product.objects.update_product(id, request.POST)
        if product_data['updated']:
            messages.success(request, "Succesfully updated {}.".format(product_data['updated_product'].name))
        else:
            for error in product_data['errors']:
                messages.error(request, error)
        return redirect(reverse('products:edit', kwargs={'id': id}))


def edit(request, id):
    context = {"product": Product.objects.get(id=id)}
    return render(request, 'products/edit.html', context)


def destroy(request, id):
    Product.objects.filter(id=id).delete()
    return redirect('/products')

apps/products/templates/products/edit.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Edit Product</title>
    </head>
    <body>
        {% if messages %}
            {% for message in messages %}
                <p>{{message}}</p>
            {% endfor %}
        {% endif %}
        <h1>Edit Product {{product.id}}</h1>
        <form action="{% url 'products:update' id=product.id %}" method="post">
            {% csrf_token %}
            <p>Name: <input type="text" name="name" value="{{product.name}}"></p>
            <p>Description: <input type="text" name="description" value="{{product.description}}"></p>
            <p>Price: <input type="text" name="price" value="{{product.price}}"></p>
            <input type="submit" value="update">
            <a href="{% url 'products:show' id=product.id %}">Show</a>
            <a href="{% url 'products:products' %}">Back</a>
        </form>
    </body>
</html>

apps/products/templates/products/new_product.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Add a new Product</title>
    </head>
    <body>
        {% if messages %}
            {% for message in messages %}
                <p>{{message}}</p>
            {% endfor %}
        {% endif %}
        <h1>Add a new product</h1>
        <form action="{% url 'products:create_new_product' %}" method="post">
            {% csrf_token %}
            <label for="name">Name
                <input type="text" name="name">
            </label>
            <label for="description">Description
                <input type="text" name="description">
            </label>
            <label for="price">Price
                <input type="text" name="price">
            </label>
            <input type="submit" value="Create">
        </form>
        <a href="{% url 'products:products' %}">Go back</a>
    </body>
</html>

apps/products/templates/products/products.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>All Products | Restful Routes</title>
        <style>
            table, tr, td {
                border: 1px solid black;
            }
        </style>
    </head>
    <body>
        <h1>Products</h1>
        <table>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Actions</th>
            </tr>
        {% for product in products %}
            <tr>
                <td>{{product.name}}</td>
                <td>{{product.description}}</td>
                <td>{{product.price}}</td>
                <td><a href="{% url 'products:show' id=product.id %}">Show</a></td>
                <td><a href="{% url 'products:edit' id=product.id %}">Edit</a></td>
                <td><a href="{% url 'products:destroy' id=product.id %}">Remove</a></td>
            </tr>
        {% endfor %}
        </table>
        <a href="{% url 'products:new_product' %}">Add a new product</a>
    </body>
</html>

apps/products/templates/products/show_product.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Product {{product.id}} Info</title>
    </head>
    <body>
        <h1>Product {{product.id}}</h1>
        <p>Name: {{product.name}}</p>
        <p>Description: {{product.description}}</p>
        <p>Price: {{product.price}}</p>
        <a href="{% url 'products:edit' id=product.id %}">Edit</a>
        <a href="{% url 'products:products' %}">Back</a>
    </body>
</html>